### ISSUE TITLE
ERROR: executing external native build for ndkBuild G:\Software\Projects\Android Projects\Android-Mod-Menu-master\app\src\main\jni\Android.mk

### ISSUE THREAD

**Issue by inder172** [LGLTeam/Android-Mod-Menu#1]
- ERROR: executing external native build for ndkBuild    Android-Mod-Menu-master\app\src\main\jni\Android.mk

- Affected Modules: app

whenever i used to compile an app i got this error.Help me!

**Comment by inder172** [comment]
![send](https://user-images.githubusercontent.com/13371417/82743302-267b9300-9d87-11ea-8ec2-a7ec59a0ed08.JPG)

**Comment by LGLTeam** [comment]
You need to install Android NDK
