### ISSUE TITLE
Crash when app is closed

### ISSUE THREAD

**Issue by ltp7509** [LGLTeam/Android-Mod-Menu#12]
**Describe the bug** 
Crash when app is closed

**Logcat**
https://prnt.sc/v1m5au

Thanks for your help

**Comment by LGLTeam** [comment]
Send your mod APK here so I can test further or send APK via private (My contact infomation is in FAQ)

**Comment by ltp7509** [comment]
please check your contact. Thank you.

**Comment by Mino260806** [comment]
Got the same error once.The problem was that I forgot to copy the lib files (*.so) from the modmenu to the game

**Comment by LGLTeam** [comment]
> Got the same error once.The problem was that I forgot to copy the lib files (*.so) from the modmenu to the game

That is true but he have different issue. It occur after he closed the game

**Comment by LGLTeam** [comment]
Closed due to inactivity. When you are back, please try latest template version
