### ISSUE TITLE
CoinMaster and a Mod Menu

### ISSUE THREAD

**Issue by virustripple** [LGLTeam/Android-Mod-Menu#14]
Hello everyone,

I need your help.

As follows I have a coin Master Version, where a mod was implemented. This mod I would like to adopt a current coin Master Version. 

Unfortunately I don't really know how to use Android Studio. So I am looking for someone who can help me or could do this.

We have been trying to do this for a long time. Unfortunately without success.

But as you can see, the mod menu design seems to come from you and the construction.

Hope to find someone on the way, who could help me
![received_366574584607027](https://user-images.githubusercontent.com/74042018/98373464-90d77580-203f-11eb-9289-ed716b7f69f4.jpeg)

**Comment by LGLTeam** [comment]
This is not the place to request for spoonfeeding

Instead, learn android developing and java programming. There are couple of tutorials online
