### ISSUE TITLE
Auto size vertically and Save feature preferences do not take effect

### ISSUE THREAD

**Issue by aylz10** [LGLTeam/Android-Mod-Menu#17]
### Describe the bug

After the Auto size vertically and Save feature preferences in 1.6 are turned on, re-entering the game's opened MOD options and Auto size vertically does not take effect. You need to re-open it, please fix

### Logcat

```
Include logcat here
If the logcat is too long, please post on pastebin.com and link here instead
```

**Comment by LGLTeam** [comment]
It is working fine for me.
Send me your modded APK privately

**Comment by aylz10** [comment]
> It is working fine for me.
> Send me your modded APK privately so I can test it

Ok i will contact you on tеlеgram

**Comment by virustripple** [comment]
we can not explain it to ourselves, after the update and took over and adapting the data, the mod no longer starts on the phone.
no matter what you do. no start function and game does not start.
ask for your help.
old function works without problems
just start picture comes. but nothing else
![received_827359871386840](https://user-images.githubusercontent.com/74042018/100143293-684fd800-2e95-11eb-8700-8691426d489c.jpeg)

**Comment by LGLTeam** [comment]
User fault.
Issue closed
