### ISSUE TITLE
Mod is not Starting CoinMaster

### ISSUE THREAD

**Issue by virustripple** [LGLTeam/Android-Mod-Menu#18]
we can not explain it to ourselves, after the update and took over and adapting the data, the mod no longer starts on the phone.
no matter what you do. no start function and game does not start.
ask for your help.
V1.4 is OK
V1.6 Is not Working (No starting Mobil Phone)

On PC is Freezing
old function works without problems
just start picture comes. but nothing else
![received_827359871386840](https://user-images.githubusercontent.com/74042018/100143566-cda3c900-2e95-11eb-9938-107ca7ee7283.jpeg)

**Comment by LGLTeam** [comment]
Not enough details. You did not use **Bug report modded game** issue template
Closed
