### ISSUE TITLE
Game crash after closing

### ISSUE THREAD

**Issue by Galaxy169** [LGLTeam/Android-Mod-Menu#19]
### Describe the bug
The game crash when I close it. It was happening in the older versions mod menu as well.
Tested it with many games and the same crash is occurring every time when I exit the game.

main.cpp doesn't have any hook or patches to make sure the crash is not caused by bad hooks or patches, I didn't touch any other files either.
Tested with Android version 5.1, 6.0 and 10, the same crash is occurring, The issue seems to be linked to the Sounds.

### Screenshot(s) or video
https://imgur.com/nmEIrB7

### Logcat

```
https://pastebin.com/sB8H4CNy
```

### Link to game
https://play.google.com/store/apps/details?id=com.fungames.sniper3d

### Link to modded APK (Optional)
https://www.mediafire.com/file/rz3oc8d7yz8o0xe/sniper-3d-fun-free-online-fps-shooting-game_3.20.1_modmenuv16.apk/file

**Comment by LGLTeam** [comment]
I can reproduce this crash. Adding` android:exported="false"` in your service like `<service android:enabled="true" android:exported="false" android:name="uk.lgl.modmenu.FloatingModMenuService" android:stopWithTask="true"/>` will fix the problem.
Please try and feedback

**Comment by Galaxy169** [comment]
> 
> 
> I can reproduce this crash. Adding `android:stopWithTask="true` in your service like `<service android:enabled="true" android:exported="false" android:name="uk.lgl.modmenu.FloatingModMenuService" android:stopWithTask="true"/>` will fix the problem.
> Please try and feedback

It's fixed! No more crashes when the app is closed. Thank You.

**Comment by LGLTeam** [comment]
Very welcome bro. I will commit with this change soon
Closed

**Comment by Mahmoud-GMG** [comment]
Bro At next update ,please add (Dialog.h) and (NativeDialog.java) i need simple dialog with image when game start .Love you Bro 💙💙

**Comment by LGLTeam** [comment]
@Mahmoud-GMG mind sending me the files privately via Telegram? @TheLGL
