### ISSUE TITLE
Problem with Memory Patch

### ISSUE THREAD

**Issue by mrcas** [LGLTeam/Android-Mod-Menu#2]
Hello,

I am using LGD Modmenu. Here is my test code:

std::string valueAttriButeConverted = "\x64\x90\xa0\xe3";

 my_cool_Patches.tempt1= MemoryPatch("il2cpp.so", 0x19E7CD0,
                                                  &valueAttriButeConverted , 4);
 my_cool_Patches.tempt1.Modify();

And valueAttrieButeConverted can be change in runtime. But when it run, the real value was patched is: "08 64 90 a0", instead of "64 90 a0 e3". I do not know where is 08 byte. 

Please help me to correct it.

**Comment by LGLTeam** [comment]
Closing this issue since the code has been customized by this user.
