### ISSUE TITLE
Smali Doesn't Crash The Game Anymore!!! : )

### ISSUE THREAD

**Issue by lilpup1414** [LGLTeam/Android-Mod-Menu#4]
Edit : I really don't know who fixed it but whoever did you are such a hero. Thank you so much it now doesn't crash immediately.

**Comment by Blink665** [comment]
what a game ?

**Comment by LGLTeam** [comment]
Can you provide the logcat errors of the game? You can use Android Studio for logcat

**Comment by LGLTeam** [comment]
Maybe i fixed it.
I still don't know what your problem was without logcat tho :/
