### ISSUE TITLE
AIDE IDE C++

### ISSUE THREAD

**Issue by kaikeSantos** [LGLTeam/Android-Mod-Menu#5]
I would like the LGL to be compatible with the AIDE NDK

**Comment by LGLTeam** [comment]
Currently no plans to support it

**Comment by LGLTeam** [comment]
Some modders have sent me the fix for AIDE, you might want to check it out https://github.com/LGLTeam/Android-Mod-Menu-AIDE-Fix

Anyway i'm now looking into AIDE support since i got a lot of requests.

**Comment by LGLTeam** [comment]
I have make AIDE support. Please read this to get started

https://github.com/LGLTeam/Android-Mod-Menu/blob/master/README-MOBILE.md
