### ISSUE TITLE
Permission apps

### ISSUE THREAD

**Issue by Quicker666** [LGLTeam/Android-Mod-Menu#6]
How do i fix permission option does not enable ? Overlay is on, I did the manifest and smali call, this my first encounter never had this problem on other games

**Comment by LGLTeam** [comment]
What do you mean by permission option does not enable? can you explain more, maybe post screenshot here?

**Comment by Quicker666** [comment]
![image](https://user-images.githubusercontent.com/51837905/95653495-b5692c00-0b2b-11eb-8a29-791385f60b3f.png)
The permission is grey out, overlay is on too but the app it just crash on start (the pic is just example it should be but its not) I tried off sound, same issue

**Comment by Quicker666** [comment]
I might have same issue with #7

**Comment by LGLTeam** [comment]
Everything is fine on my side
Provide your logcat and filter only Errors. That way I can see what went wrong

https://developer.android.com/studio/debug/am-logcat

Without proper details, this issue would be closed

**Comment by LGLTeam** [comment]
Please update the template as i fixed some issues. Re-open if you got any details
