### ISSUE TITLE
smali files crashing

### ISSUE THREAD

**Issue by yashmanghnani** [LGLTeam/Android-Mod-Menu#7]
After implementation in apk the application doesn't ask for floating permission. Even we give floating permission forcefully to the app then app will start crashing on launch activity. 
Before this update everything is working properly , kindly fix this problem as soon as possible .
Thank you

**Comment by LGLTeam** [comment]
Please explain in detail how you are adding menu to the game step by step, and provide logcat of the game

**Comment by LGLTeam** [comment]
Please update the template as i fixed some issues. Re-open if you got any details and logcat
